apiVersion: v1
kind: Service
metadata:
  name: astrago-experiment-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.experiment.service.type }}
  ports:
    - port: {{ .Values.experiment.service.port }}
      targetPort: {{ .Values.experiment.service.port }}
      nodePort: {{ .Values.experiment.service.nodePort }}
      protocol: TCP
      name: http
  selector: 
    app.kubernetes.io/name: astrago-experiment-hub
